### ISSUE TITLE
[Bug] Calendar not affected by Darkmode for all users

### ISSUE THREAD

**Issue by Rathmox** [CustomDirecte/CustomDirecte#11]
> [Bug] - Calendar not affected by Darkmode for all users - @Rathmox 

**Détails techniques :**
Image ci-dessous.
Navigateur : Firefox

![image](https://github.com/Bastian-Noel/CustomDirecte/assets/55508107/2bce0ae2-f685-47a5-8423-20f8692b8f9f)

**Comment by Bastian-Noel** [comment]
Mon navigateur Firefox :
![image](https://github.com/Bastian-Noel/CustomDirecte/assets/71983581/fb2ca018-d9de-4ed0-8bc1-34167a97b80e)

**Comment by Bastian-Noel** [comment]
Si possible j'aimerais bien te contacter sur discord pour pouvoir te poser des questions,ou de demander des manipulations si cela te gêne pas.

Le server discord du projet : https://discord.gg/WJtuEa97g6

**Comment by Rathmox** [comment]
> Il faut savoir que le darkmode est une integration du projet [Darkreader ](https://github.com/darkreader/darkreader), et donc que les bugs ont de forte chance d'y être lié.
> 
> Exemple de navigateur Firefox en temps normal :
> ![image](https://github.com/Bastian-Noel/CustomDirecte/assets/71983581/fb2ca018-d9de-4ed0-8bc1-34167a97b80e)
> 

Darkreader change correctement la couleur du calendrier

**Comment by Bastian-Noel** [comment]
Le dark mode est refait dans la prochaine version et devrais résoudre ce bug !

**Comment by Rathmox** [comment]
il a été résolu, vu que je l'ai moi-même testé
