### ISSUE TITLE
[Bug] Sidebar submenu overlay display

### ISSUE THREAD

**Issue by Rathmox** [CustomDirecte/CustomDirecte#12]
> [Bug] - sidebar submenu overlay display - @Rathmox 

**Détails techniques :**
Image ci-dessous.
Navigateur : Firefox

![image](https://github.com/Bastian-Noel/CustomDirecte/assets/55508107/34500bbe-f7e2-4f97-9845-3d6e4ee1ce36)

**Comment by Bastian-Noel** [comment]
Si possible j'aimerais bien te contacter sur discord pour pouvoir te poser des questions,ou de demander des manipulations si cela te gêne pas.

Le server discord du projet : https://discord.gg/WJtuEa97g6

**Comment by Rathmox** [comment]
> J'aurais besion du code HTML de ton side bar pour corriger le bug !
> 
> Si possible j'aimerais bien te contacter sur discord pour pouvoir te poser des questions, ou de demander des manipulations si cela te gêne pas.
> 
> Le server discord du projet : https://discord.gg/WJtuEa97g6

C'est un script qui modifie la page pour afficher ça.

```
<li>
    <ed-menu-block-item>
        <div>
            <a>
                <i class="icon-ed_esidoc"></i><span class="item-name">Portails E-sidoc</span>
                <i class="fa fa-chevron-up"></i>
            </a>
            <a edgotoservice="" class="external ng-star-inserted">
                <i aria-hidden="true" class="fa fa-external-link"></i><span class="item-name">CDI Site [...]</span>
            </a>
            <a edgotoservice="" class="external ng-star-inserted">
                <i aria-hidden="true" class="fa fa-external-link"></i><span class="item-name">CDI Site [...]</span>
            </a>
            <a edgotoservice="" class="external ng-star-inserted">
                <i aria-hidden="true" class="fa fa-external-link"></i><span class="item-name">CDI Site [...]</span>
            </a>
        </div>
    </ed-menu-block-item>
</li>
```

J'ai reformaté le code et retiré les noms de lieux. Je sais pas si juste la partie du bouton est nécessaire ou si toute la sidebar était mieux.
