### ISSUE TITLE
Mettre à jour la version Firefox

### ISSUE THREAD

**Issue by s1w2a3** [CustomDirecte/CustomDirecte#14]
**Détails techniques :**
La bêta 6.2.0 fonctionne bien sur Chrome, mais la version Firefox est toujours en 6.1.1
Serait-il possible de déployer la nouvelle version sur Firefox aussi ?

**Commentaire :**
Merci pour cette extension très utile !

**Comment by Bastian-Noel** [comment]
La prochaine version est en cours de transfer vers firefox mais il y a beaucoup de complications ! Normalement elle sortira ce WE sur chrome et firefox !
