### ISSUE TITLE
[SUGGESTION] Ajouter l'onglet badge cantine présent sur mobile sur le site web pour pouvoir remplacer l'application mobile

### ISSUE THREAD

**Issue by Fefedu973** [CustomDirecte/CustomDirecte#17]

**Comment by Fefedu973** [comment]
Je peux aider mais nécessite l'accès à l'api

**Comment by Bastian-Noel** [comment]
# Utilisation de l'API dans CustomDirecte

Cher utilisateur de CustomDirecte,

Nous apprécions grandement votre intérêt pour CustomDirecte et vos suggestions concernant de nouvelles fonctionnalités pour notre extension Chrome. Cependant, nous tenons à vous informer que l'utilisation de l'API du site est une pratique litigieuse et ne correspond pas à la politique de CustomDirecte.

Notre engagement envers nos utilisateurs et le site est primordial. L'utilisation non autorisée de l'API peut entraîner des violations des termes d'utilisation et des droits d'auteur du site, ce qui peut avoir des conséquences légales.

Nous comprenons que vous puissiez souhaiter des fonctionnalités supplémentaires, et nous encourageons vivement les suggestions qui respectent les règles et les politiques en vigueur. CustomDirecte vise à offrir une expérience utilisateur optimale tout en maintenant une conformité éthique et légale.

Si vous avez des idées pour des fonctionnalités qui ne nécessitent pas l'utilisation de l'API du site, nous serions ravis de les entendre et de les considérer pour de futures mises à jour de CustomDirecte.

Merci de votre compréhension et de votre soutien continu.

Cordialement,
L'équipe CustomDirecte

**Comment by Fefedu973** [comment]
Ceci n'est qu'une suggestion et je peux m'occuper du code entièrement si sa vous embête mais sans faire de requête api on pourrait intégrer un système similaire à https://ed-badge-bypass.fr/ dans les paramètres pour créée son badge et l'ajouter dans l'onglet. Cela permettrait une totale parité de fonctionnalités entre mobile et desktop
