### ISSUE TITLE
[BUG] Affichage du nom/prénom dépassant de l'espace dédié

### ISSUE THREAD

**Issue by Fefedu973** [CustomDirecte/CustomDirecte#22]
Avec un nom/prénom assez long le nom est coupé et personnelement une lettre à disparue (premier charactère de mon nom de famille) et l'espace entre mon nom et mon prénom est également coupé

**Comment by Bastian-Noel** [comment]
# Bug pris en compte

Cher utilisateur de CustomDirecte,

Merci pour votre vigilance ! Nous avons pris note du bug que vous avez signalé et sommes heureux de vous informer qu'il sera résolu dans les prochaines versions de CustomDirecte. Votre contribution à l'amélioration de notre extension est précieuse.

Restez à l'affût des mises à jour à venir, et n'hésitez pas à nous informer si vous découvrez d'autres problèmes. Merci pour votre collaboration continue !

Cordialement,
L'équipe CustomDirecte
